### ISSUE TITLE
Assertion Failed: Invalid AABB a ...

### ISSUE THREAD

**Issue by Spyispie120** [PickleGames/SealTheDeal#39]
![screenshot_2](https://user-images.githubusercontent.com/12041033/29442830-f8912fce-8388-11e7-870e-93dc87a39c77.png)

Don't know what caused this.

**Comment by Spyispie120** [comment]
Fixed.

Problem seem to caused by the bound of character mesh renderer

**Comment by faaataaan** [comment]
How to fixed?
